### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MilchRatchet** [MilchRatchet/PAL#1]
We should add a licence, without it people are only ever allowed to view or fork this project but they are not allowed to use any of it. I would say we should just use the `zlib` licence, details can be found here https://github.com/MilchRatchet/Luminary/blob/main/LICENCE

What do you think?

**Comment by Mathemalsky** [comment]
I think we can do it the way you suggested.

**Comment by MilchRatchet** [comment]
Ok, I added the licence.
