### ISSUE TITLE
failed to install libsdl2

### ISSUE THREAD

**Issue by Mathemalsky** [MilchRatchet/PAL#5]
![Bildschirmfoto von 2021-06-25 22-32-25](https://user-images.githubusercontent.com/78656598/123482447-7cafab00-d605-11eb-8d81-68f526909cdf.png)
I couldn't install the library and all my tries to google it are lacking success.

**Comment by MilchRatchet** [comment]
Did you try commands like `sudo apt-get -f install` yet? Alternatively you could simply install the dependencies first. From what I have read it could also be that your local package database is too old and you need to upgrade using
```
sudo apt-get update && sudo apt-get full-upgrade
```

I think there is something weird with your package manager since you also could not install CUDA. You could try using `aptitude` which is apparently better at resolving dependency issues.

**Comment by Mathemalsky** [comment]
Yes I tried `sudo apt-get -f install` yesterday.
Manually installing the dependencies first does not work since the packages are not installable as printed out to the terminal.
Yes also also tried the `update` and `upgrade` commands but they do not change anything.
I also suspect the cuda drivers to be the root of the package trouble.

Is there a way to reset the complete installed packgages without reinstalling the system (configuring takes too much time)?

**Comment by MilchRatchet** [comment]
I don't know what you mean with "reset the complete installed packgages".

I just realized that the error given is that you have held back packages. You can do `apt-mark showhold` to display them and then unhold them by `sudo apt-mark unhold [name of package]`. If that does not work, you should try `aptitude`, many people say that they fixed this issue by installing it that way.

**Comment by Mathemalsky** [comment]
Oh yes I forgot to mention that I also tried `aptitude` and it gave the same output as `apt-get`. See the attached screenshot. I'm not sure about choosing an option there.
The List displayed by `apt-mark showhold` is empty. 
![grafik](https://user-images.githubusercontent.com/78656598/123507910-8f10ff80-d66c-11eb-99d6-191587754d3d.png)

**Comment by MilchRatchet** [comment]
It seems to be an issue with the repository where apt searches. With `cat /etc/apt/sources.list /etc/apt/sources.list.d/*` you can view the repository list. Any line starting with `deb` indicates a repository it uses. I seem to use the groovy distribution of the default ubuntu repository.

**Comment by Mathemalsky** [comment]
What is your suggestion to deal with that?
